locale          : "en-US"
url             : https://aassumpcao.github.io
repository      : "aassumpcao.github.io"

staticman:
  branch: "master"

analytics:
  provider      :  "google-gtag"
  google:
    tracking_id :  "UA-131557431-1"

include:
  - files
  - style

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
